[package]
name = "fir-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
fir-core.workspace = true
fir-mir.workspace = true
tracing.workspace = true
salsa.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
