[package]
name = "fir-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
fir-core.workspace = true
fir-mir.workspace = true
salsa.workspace = true
cranelift-entity.workspace = true
bumpalo.workspace = true
bytemuck.workspace = true
