[package]
name = "fir-mir-filetests"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
salsa.workspace = true
fir-mir.workspace = true
fir-core.workspace = true
pretty_assertions.workspace = true

[build-dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
